# Generated by Django 3.1.7 on 2021-07-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrar_exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=32, verbose_name='Exercicio')),
                ('repetições', models.CharField(default='3x12', max_length=4, verbose_name='Repetições')),
            ],
        ),
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('nome', models.CharField(max_length=40, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros'), ('NI', 'Não Informado')], max_length=3, null=True, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=240, verbose_name='Endereço')),
                ('data_da_matricula', models.DateField(auto_now_add=True, verbose_name='Data da Matricula')),
                ('data_de_vencimento', models.DateField(verbose_name='Vencimento')),
                ('foto_aluno', models.ImageField(blank=True, null=True, upload_to='alunos', verbose_name='Foto do Aluno')),
                ('plano', models.CharField(choices=[('1', 'Musculação'), ('2', 'Cross'), ('3', 'Musculação + Cross')], max_length=2, verbose_name='Plano')),
                ('valor', models.CharField(max_length=6, verbose_name='Subtotal')),
                ('desconto', models.CharField(blank=True, max_length=5, verbose_name='Desconto')),
                ('valor_total', models.CharField(max_length=6, verbose_name='Valor da Mensalidade')),
                ('num_matricula', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Número da Matricula')),
                ('observacoes', models.TextField(blank=True, max_length=512, null=True, verbose_name='Obeservações')),
            ],
        ),
        migrations.CreateModel(
            name='treinoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aexc_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino1', to='gerenciar.cadastrar_exercicio', verbose_name='1')),
                ('aexc_10', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino10', to='gerenciar.cadastrar_exercicio', verbose_name='10')),
                ('aexc_11', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino11', to='gerenciar.cadastrar_exercicio', verbose_name='11')),
                ('aexc_12', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino12', to='gerenciar.cadastrar_exercicio', verbose_name='12')),
                ('aexc_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino2', to='gerenciar.cadastrar_exercicio', verbose_name='2')),
                ('aexc_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino3', to='gerenciar.cadastrar_exercicio', verbose_name='3')),
                ('aexc_4', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino4', to='gerenciar.cadastrar_exercicio', verbose_name='4')),
                ('aexc_5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino5', to='gerenciar.cadastrar_exercicio', verbose_name='5')),
                ('aexc_6', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino6', to='gerenciar.cadastrar_exercicio', verbose_name='6')),
                ('aexc_7', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino7', to='gerenciar.cadastrar_exercicio', verbose_name='7')),
                ('aexc_8', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino8', to='gerenciar.cadastrar_exercicio', verbose_name='8')),
                ('aexc_9', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treino9', to='gerenciar.cadastrar_exercicio', verbose_name='9')),
                ('nome', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciar.matricula', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulina', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Insulina')),
                ('antidepressivos', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Antidepressivos')),
                ('antihistaminicos', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Anti-Histaminicos (Alergia)')),
                ('betabloqueadores', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Betabloqueadores (Hipertensão)')),
                ('analgesicos', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Analgésicos')),
                ('ansiolitico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Ansiolítico (Ansiedade)')),
                ('suplementos_vit', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2, verbose_name='Suplementos Vitamínicos')),
                ('observacoes', models.TextField(blank=True, max_length=140, null=True, verbose_name='Observações')),
                ('nome', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciar.matricula', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField(verbose_name='Entrada')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Saída')),
                ('data', models.DateField(auto_now_add=True)),
                ('nome', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='gerenciar.matricula', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_de_saude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Diabetes')),
                ('hipertensao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Hipertensão')),
                ('artrite', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Artrite')),
                ('artrose', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Artrose')),
                ('reumatismo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Reumatismo')),
                ('doencas_cardiacas', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Doenças Cardiacas')),
                ('avc', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Já Sofreu AVC')),
                ('fuma', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Tabagismo')),
                ('bebe', models.CharField(choices=[('S', 'Sempre que Posso'), ('O', 'Ocasionalmente'), ('R', 'Raramente'), ('N', 'Não Bebo')], max_length=1, null=True, verbose_name='Bebe')),
                ('nome', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciar.matricula', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Idade')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='altura')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='IMC')),
                ('cintura', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Circunferência Cintura (cm)')),
                ('quadril', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Circunferência Quadril (cm)')),
                ('rcq', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='RCQ')),
                ('d1', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tricipital')),
                ('d2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Bicipital')),
                ('d3', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Subescapular')),
                ('d4', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Torácica')),
                ('d5', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Axilar Média')),
                ('d6', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Supra-Ilíaca')),
                ('d7', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cutânea Abdominal')),
                ('d8', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cutânea da Coxa')),
                ('gordura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='% de Gordura')),
                ('nome', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gerenciar.matricula', verbose_name='Aluno')),
            ],
        ),
    ]
